sonar.projectKey=g5-laboratory-management-and-control-system
sonar.projectName=g5-laboratory-management-and-control-system
sonar.host.url=https://server2.distribuidauce.org

# Fuentes del monorepo
sonar.sources=services/api-gateway/src,services/auth-service/src,services/catalog-service/src,services/incident-service/src,services/laboratory-service/src,services/logger-service/src,services/notification-service/src,services/payment-service/src,services/reservation-service/src,apps/frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.html

# Cobertura de SAST
sonar.javascript.lcov.reportPaths=services/*/coverage/lcov.info

# Reportes de SCA (OWASP Dependency-Check)
sonar.dependencyCheck.jsonReportPath=reports/dependency-check-report.json
sonar.dependencyCheck.htmlReportPath=reports/dependency-check-report.html
