export enum NotificationType {
  RESERVATION_CREATED = 'RESERVATION_CREATED',
  RESERVATION_CONFIRMED = 'RESERVATION_CONFIRMED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  LABORATORY_UPDATE = 'LABORATORY_UPDATE',
}
