export const INITIAL_LABORATORIES = [
  // Área: Computación y Desarrollo de Software
  {
    name: 'Laboratorio Computación 01',
    description: 'Laboratorio estándar para ofimática e introducción a la programación.',
    location: 'Facultad de Ingeniería - Piso 1 - Sala 101',
    max_capacity: 30,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio Computación 02',
    description: 'Laboratorio estándar para ofimática e introducción a la programación.',
    location: 'Facultad de Ingeniería - Piso 1 - Sala 102',
    max_capacity: 30,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio Computación 03',
    description: 'Laboratorio equipado para desarrollo web y diseño gráfico.',
    location: 'Facultad de Ingeniería - Piso 1 - Sala 103',
    max_capacity: 25,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Desarrollo Móvil',
    description: 'Equipos Mac y PC de gama alta para emulación y desarrollo de apps iOS/Android.',
    location: 'Facultad de Ingeniería - Piso 2 - Sala 201',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Videojuegos',
    description: 'Estaciones de trabajo con GPUs dedicadas para Unity y Unreal Engine.',
    location: 'Facultad de Ingeniería - Piso 2 - Sala 202',
    max_capacity: 15,
    status: 'MAINTENANCE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Sistemas Operativos',
    description: 'Sala aislada para prácticas de instalación y configuración de SO (Linux/Windows).',
    location: 'Facultad de Ingeniería - Piso 2 - Sala 203',
    max_capacity: 25,
    status: 'ACTIVE',
    tier: 'BASIC',
  },

  // Área: Redes, Seguridad y Datos
  {
    name: 'Laboratorio de Redes Cisco 1',
    description: 'Equipamiento físico de routers y switches Cisco para prácticas de CCNA.',
    location: 'Torre Tecnológica - Piso 3 - Sala 301',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Redes Cisco 2',
    description: 'Equipamiento avanzado para enrutamiento y conmutación.',
    location: 'Torre Tecnológica - Piso 3 - Sala 302',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Ciberseguridad',
    description: 'Entorno aislado para prácticas de hacking ético y análisis de vulnerabilidades.',
    location: 'Torre Tecnológica - Piso 4 - Sala 401',
    max_capacity: 15,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Bases de Datos',
    description: 'Servidores locales para prácticas de SQL, NoSQL y administración de DBs.',
    location: 'Torre Tecnológica - Piso 4 - Sala 402',
    max_capacity: 30,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Big Data',
    description: 'Clústeres de procesamiento para Hadoop y Spark.',
    location: 'Torre Tecnológica - Piso 4 - Sala 403',
    max_capacity: 25,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Inteligencia Artificial',
    description: 'Workstations con Tensor Cores para entrenamiento de modelos Deep Learning.',
    location: 'Torre Tecnológica - Piso 5 - Sala 501',
    max_capacity: 15,
    status: 'ACTIVE',
    tier: 'BASIC',
  },

  // Área: Física
  {
    name: 'Laboratorio de Física Clásica A',
    description: 'Equipos para experimentos de mecánica y cinemática.',
    location: 'Edificio de Ciencias - PB - Sala 01',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Física Clásica B',
    description: 'Equipos para experimentos de mecánica y cinemática.',
    location: 'Edificio de Ciencias - PB - Sala 02',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Electromagnetismo',
    description: 'Fuentes de poder, osciloscopios y kits de magnetismo.',
    location: 'Edificio de Ciencias - Piso 1 - Sala 11',
    max_capacity: 25,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Óptica',
    description: 'Mesas ópticas, láseres y lentes para prácticas de luz y refracción.',
    location: 'Edificio de Ciencias - Piso 1 - Sala 12',
    max_capacity: 15,
    status: 'INACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Termodinámica',
    description: 'Calorímetros y equipos de medición térmica.',
    location: 'Edificio de Ciencias - Piso 2 - Sala 21',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Física Moderna',
    description: 'Equipos de precisión para experimentos de física cuántica básica.',
    location: 'Edificio de Ciencias - Piso 2 - Sala 22',
    max_capacity: 10,
    status: 'MAINTENANCE',
    tier: 'BASIC',
  },

  // Área: Química
  {
    name: 'Laboratorio de Química General 1',
    description: 'Mesones con extractores, mecheros Bunsen y material de vidrio.',
    location: 'Pabellón de Química - Piso 1 - Lab 1',
    max_capacity: 30,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Química General 2',
    description: 'Mesones con extractores, mecheros Bunsen y material de vidrio.',
    location: 'Pabellón de Química - Piso 1 - Lab 2',
    max_capacity: 30,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Química Orgánica',
    description: 'Campanas de extracción de gases para síntesis orgánica.',
    location: 'Pabellón de Química - Piso 2 - Lab 3',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Química Analítica',
    description: 'Equipos de titulación, espectrofotómetros y balanzas analíticas.',
    location: 'Pabellón de Química - Piso 2 - Lab 4',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Fisicoquímica',
    description: 'Instrumentación avanzada para medir propiedades físicas de compuestos.',
    location: 'Pabellón de Química - Piso 3 - Lab 5',
    max_capacity: 15,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Análisis Instrumental',
    description: 'Cromatógrafos de gases y líquidos (HPLC).',
    location: 'Pabellón de Química - Piso 3 - Lab 6',
    max_capacity: 10,
    status: 'MAINTENANCE',
    tier: 'BASIC',
  },

  // Área: Biología y Medicina
  {
    name: 'Laboratorio de Biología General',
    description: 'Microscopios ópticos y muestras biológicas preparadas.',
    location: 'Facultad de Biología - Piso 1 - Sala 1',
    max_capacity: 30,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Microbiología',
    description: 'Autoclaves, incubadoras y cabinas de flujo laminar.',
    location: 'Facultad de Biología - Piso 2 - Sala 2',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Genética',
    description: 'Equipos PCR, centrífugas y electroforesis.',
    location: 'Facultad de Biología - Piso 3 - Sala 3',
    max_capacity: 15,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Anatomía',
    description: 'Mesas de disección y modelos anatómicos 3D.',
    location: 'Facultad de Medicina - Subsuelo - Sala A',
    max_capacity: 40,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Histología',
    description: 'Colección de tejidos y microscopios de alta resolución.',
    location: 'Facultad de Medicina - Piso 1 - Sala B',
    max_capacity: 25,
    status: 'INACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Centro de Simulación Médica',
    description: 'Maniquíes interactivos para prácticas de primeros auxilios y UCI.',
    location: 'Facultad de Medicina - Piso 2 - Sala C',
    max_capacity: 15,
    status: 'ACTIVE',
    tier: 'BASIC',
  },

  // Área: Electrónica y Telecomunicaciones
  {
    name: 'Laboratorio de Circuitos Eléctricos',
    description: 'Protoboards, multímetros y fuentes de voltaje.',
    location: 'Facultad de Electrónica - Piso 1 - Lab A',
    max_capacity: 25,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Electrónica Analógica',
    description: 'Osciloscopios y generadores de señales.',
    location: 'Facultad de Electrónica - Piso 1 - Lab B',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Electrónica Digital',
    description: 'Kits FPGA y microcontroladores básicos.',
    location: 'Facultad de Electrónica - Piso 2 - Lab C',
    max_capacity: 25,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Microprocesadores',
    description: 'Kits de desarrollo Arduino, Raspberry Pi y STM32.',
    location: 'Facultad de Electrónica - Piso 2 - Lab D',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Telecomunicaciones 1',
    description: 'Antenas, analizadores de espectro y radios.',
    location: 'Facultad de Electrónica - Piso 3 - Lab E',
    max_capacity: 15,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Fibra Óptica',
    description: 'Empalmadoras de fibra y OTDRs.',
    location: 'Facultad de Electrónica - Piso 3 - Lab F',
    max_capacity: 12,
    status: 'MAINTENANCE',
    tier: 'BASIC',
  },

  // Robótica, Mecatrónica y Civil
  {
    name: 'Laboratorio de Robótica Industrial',
    description: 'Brazos robóticos articulados para prácticas de manufactura.',
    location: 'Centro de Innovación - Nave 1',
    max_capacity: 15,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Robótica Móvil',
    description: 'Pista de pruebas y robots móviles autónomos (AGV).',
    location: 'Centro de Innovación - Nave 2',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Control y Automatización',
    description: 'PLCs Siemens y paneles de control industrial.',
    location: 'Centro de Innovación - Nave 3',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Diseño CAD/CAM',
    description: 'Estaciones de trabajo de alto rendimiento e impresoras 3D.',
    location: 'Centro de Diseño - Sala 1',
    max_capacity: 25,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Mecánica de Suelos',
    description: 'Prensas hidráulicas y tamices para pruebas de tierra.',
    location: 'Facultad de Ingeniería Civil - PB',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Hidráulica',
    description: 'Canales de flujo y bombas de agua para mecánica de fluidos.',
    location: 'Facultad de Ingeniería Civil - Ext',
    max_capacity: 15,
    status: 'INACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Topografía',
    description: 'Almacenamiento de teodolitos, estaciones totales y drones.',
    location: 'Facultad de Ingeniería Civil - Piso 1',
    max_capacity: 20,
    status: 'ACTIVE',
    tier: 'BASIC',
  },

  // Salas de Uso Múltiple y Estructuras Especiales
  {
    name: 'Sala de Computación Libre A',
    description: 'Computadoras de libre acceso para tareas y consultas.',
    location: 'Biblioteca Central - Piso 1',
    max_capacity: 50,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Sala de Computación Libre B',
    description: 'Computadoras de libre acceso para tareas y consultas.',
    location: 'Biblioteca Central - Piso 2',
    max_capacity: 50,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Idiomas 1',
    description: 'Cabinas con audífonos aislantes y software de aprendizaje.',
    location: 'Centro de Idiomas - Piso 1',
    max_capacity: 30,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Idiomas 2',
    description: 'Cabinas con audífonos aislantes y software de aprendizaje.',
    location: 'Centro de Idiomas - Piso 2',
    max_capacity: 30,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Taller de Arquitectura',
    description: 'Mesas amplias para maquetación y dibujo técnico.',
    location: 'Facultad de Arquitectura - Sala Magna',
    max_capacity: 40,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
  {
    name: 'Estudio de Grabación Audiovisual',
    description: 'Cámaras, pantallas verdes e insonorización profesional.',
    location: 'Facultad de Artes - Estudio 1',
    max_capacity: 10,
    status: 'MAINTENANCE',
    tier: 'BASIC',
  },
  {
    name: 'Laboratorio de Edición de Video',
    description: 'Equipos Apple Mac Studio para renderizado 4K.',
    location: 'Facultad de Artes - Sala 2',
    max_capacity: 15,
    status: 'ACTIVE',
    tier: 'BASIC',
  },
];
