name: Terraform — Apply

on:
  push:
    branches: [main, qa]
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/terraform-apply.yml'

env:
  AWS_ACCESS_KEY_ID: ${{ github.ref == 'refs/heads/main' && secrets.PROD_AWS_ACCESS_KEY_ID || secrets.QA_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PROD_AWS_SECRET_ACCESS_KEY || secrets.QA_AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.PROD_AWS_SESSION_TOKEN || secrets.QA_AWS_SESSION_TOKEN }}
  AWS_REGION: us-east-1

jobs:
  terraform-apply:
    name: Terraform Apply (${{ github.ref == 'refs/heads/main' && 'Production' || 'QA' }})
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'qa' }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verificar variables de backend S3
        run: |
          if [ -z "${{ vars.TF_STATE_BUCKET }}" ]; then
            echo "::error::Falta TF_STATE_BUCKET en el Environment configurado."
            exit 1
          fi

      - name: Terraform Init (S3 backend)
        working-directory: infra/terraform/environments/${{ github.ref == 'refs/heads/main' && 'prod' || 'qa' }}
        env:
          TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
          TF_AWS_REGION: ${{ vars.TF_AWS_REGION }}
        run: bash ../../scripts/init-backend.sh ${{ github.ref == 'refs/heads/main' && 'prod' || 'qa' }}

      - name: Terraform Apply
        working-directory: infra/terraform/environments/${{ github.ref == 'refs/heads/main' && 'prod' || 'qa' }}
        run: |
          terraform apply -auto-approve \
            -var="enable_rds=false" \
            ${{ github.ref == 'refs/heads/main' && format('-var="db_password={0}"', secrets.DB_PASSWORD) || '' }} \
            ${{ github.ref == 'refs/heads/main' && format('-var="jwt_secret={0}"', secrets.JWT_SECRET) || '' }} \
            -var="image_tag=${{ github.ref == 'refs/heads/main' && 'prod' || 'qa' }}"

      - name: Mostrar outputs
        working-directory: infra/terraform/environments/${{ github.ref == 'refs/heads/main' && 'prod' || 'qa' }}
        run: terraform output
